export interface Icd10Code {
  code: string;
  description: string;
  category: string;
}

export const ICD10_CODES: Icd10Code[] = [
  // Cardiovascular
  { code: "I10", description: "Essential (primary) hypertension", category: "Cardiovascular" },
  { code: "I11.0", description: "Hypertensive heart disease with heart failure", category: "Cardiovascular" },
  { code: "I20.0", description: "Unstable angina", category: "Cardiovascular" },
  { code: "I21.09", description: "ST elevation myocardial infarction involving other coronary artery of anterior wall", category: "Cardiovascular" },
  { code: "I21.19", description: "ST elevation myocardial infarction involving other coronary artery of inferior wall", category: "Cardiovascular" },
  { code: "I21.4", description: "Non-ST elevation myocardial infarction", category: "Cardiovascular" },
  { code: "I25.10", description: "Atherosclerotic heart disease of native coronary artery", category: "Cardiovascular" },
  { code: "I25.2", description: "Old myocardial infarction", category: "Cardiovascular" },
  { code: "I35.0", description: "Nonrheumatic aortic (valve) stenosis", category: "Cardiovascular" },
  { code: "I42.9", description: "Cardiomyopathy, unspecified", category: "Cardiovascular" },
  { code: "I44.2", description: "Atrioventricular block, complete", category: "Cardiovascular" },
  { code: "I47.1", description: "Supraventricular tachycardia", category: "Cardiovascular" },
  { code: "I48.0", description: "Paroxysmal atrial fibrillation", category: "Cardiovascular" },
  { code: "I48.91", description: "Unspecified atrial fibrillation", category: "Cardiovascular" },
  { code: "I50.9", description: "Heart failure, unspecified", category: "Cardiovascular" },
  { code: "I50.22", description: "Chronic systolic (congestive) heart failure", category: "Cardiovascular" },
  { code: "I50.32", description: "Chronic diastolic (congestive) heart failure", category: "Cardiovascular" },
  { code: "I63.9", description: "Cerebral infarction, unspecified", category: "Cardiovascular" },
  { code: "I65.29", description: "Occlusion and stenosis of unspecified carotid artery", category: "Cardiovascular" },
  { code: "I70.203", description: "Unspecified atherosclerosis of native arteries of bilateral legs", category: "Cardiovascular" },
  { code: "I73.9", description: "Peripheral vascular disease, unspecified", category: "Cardiovascular" },
  { code: "I80.202", description: "Phlebitis and thrombophlebitis of unspecified deep vessels of left lower extremity", category: "Cardiovascular" },
  { code: "I82.4Z1", description: "Acute embolism and thrombosis of unspecified deep veins of right lower extremity", category: "Cardiovascular" },
  { code: "I95.1", description: "Orthostatic hypotension", category: "Cardiovascular" },
  { code: "R00.1", description: "Bradycardia, unspecified", category: "Cardiovascular" },
  { code: "R00.0", description: "Tachycardia, unspecified", category: "Cardiovascular" },
  { code: "R07.9", description: "Chest pain, unspecified", category: "Cardiovascular" },

  // Respiratory
  { code: "J18.9", description: "Pneumonia, unspecified organism", category: "Respiratory" },
  { code: "J15.9", description: "Unspecified bacterial pneumonia", category: "Respiratory" },
  { code: "J20.9", description: "Acute bronchitis, unspecified", category: "Respiratory" },
  { code: "J44.0", description: "Chronic obstructive pulmonary disease with acute lower respiratory infection", category: "Respiratory" },
  { code: "J44.1", description: "Chronic obstructive pulmonary disease with acute exacerbation", category: "Respiratory" },
  { code: "J44.9", description: "Chronic obstructive pulmonary disease, unspecified", category: "Respiratory" },
  { code: "J45.20", description: "Mild intermittent asthma, uncomplicated", category: "Respiratory" },
  { code: "J45.40", description: "Moderate persistent asthma, uncomplicated", category: "Respiratory" },
  { code: "J45.909", description: "Unspecified asthma, uncomplicated", category: "Respiratory" },
  { code: "J81.0", description: "Acute pulmonary edema", category: "Respiratory" },
  { code: "J84.10", description: "Pulmonary fibrosis, unspecified", category: "Respiratory" },
  { code: "J90", description: "Pleural effusion, not elsewhere classified", category: "Respiratory" },
  { code: "J93.0", description: "Spontaneous tension pneumothorax", category: "Respiratory" },
  { code: "J96.00", description: "Acute respiratory failure, unspecified whether with hypoxia or hypercapnia", category: "Respiratory" },
  { code: "J96.01", description: "Acute respiratory failure with hypoxia", category: "Respiratory" },
  { code: "J96.02", description: "Acute respiratory failure with hypercapnia", category: "Respiratory" },
  { code: "J98.01", description: "Acute bronchospasm", category: "Respiratory" },
  { code: "R05.9", description: "Cough, unspecified", category: "Respiratory" },
  { code: "R06.02", description: "Shortness of breath", category: "Respiratory" },
  { code: "R06.00", description: "Dyspnea, unspecified", category: "Respiratory" },
  { code: "R09.02", description: "Hypoxemia", category: "Respiratory" },
  { code: "U07.1", description: "COVID-19", category: "Respiratory" },

  // Endocrine / Metabolic
  { code: "E11.9", description: "Type 2 diabetes mellitus without complications", category: "Endocrine" },
  { code: "E11.21", description: "Type 2 diabetes mellitus with diabetic nephropathy", category: "Endocrine" },
  { code: "E11.22", description: "Type 2 diabetes mellitus with diabetic chronic kidney disease", category: "Endocrine" },
  { code: "E11.40", description: "Type 2 diabetes mellitus with diabetic neuropathy, unspecified", category: "Endocrine" },
  { code: "E11.65", description: "Type 2 diabetes mellitus with hyperglycemia", category: "Endocrine" },
  { code: "E10.9", description: "Type 1 diabetes mellitus without complications", category: "Endocrine" },
  { code: "E03.9", description: "Hypothyroidism, unspecified", category: "Endocrine" },
  { code: "E05.90", description: "Thyrotoxicosis, unspecified without thyrotoxic crisis or storm", category: "Endocrine" },
  { code: "E66.01", description: "Morbid (severe) obesity due to excess calories", category: "Endocrine" },
  { code: "E66.9", description: "Obesity, unspecified", category: "Endocrine" },
  { code: "E78.5", description: "Hyperlipidemia, unspecified", category: "Endocrine" },
  { code: "E78.00", description: "Pure hypercholesterolemia, unspecified", category: "Endocrine" },
  { code: "E83.42", description: "Hypomagnesemia", category: "Endocrine" },
  { code: "E86.0", description: "Dehydration", category: "Endocrine" },
  { code: "E87.1", description: "Hypo-osmolality and hyponatremia", category: "Endocrine" },
  { code: "E87.5", description: "Hyperkalemia", category: "Endocrine" },
  { code: "E87.6", description: "Hypokalemia", category: "Endocrine" },
  { code: "E88.81", description: "Metabolic syndrome", category: "Endocrine" },

  // Gastrointestinal
  { code: "K21.0", description: "Gastro-esophageal reflux disease with esophagitis", category: "Gastrointestinal" },
  { code: "K21.9", description: "Gastro-esophageal reflux disease without esophagitis", category: "Gastrointestinal" },
  { code: "K25.9", description: "Gastric ulcer, unspecified as acute or chronic, without hemorrhage or perforation", category: "Gastrointestinal" },
  { code: "K29.70", description: "Gastritis, unspecified, without bleeding", category: "Gastrointestinal" },
  { code: "K35.80", description: "Unspecified acute appendicitis", category: "Gastrointestinal" },
  { code: "K40.90", description: "Unilateral inguinal hernia, without obstruction or gangrene", category: "Gastrointestinal" },
  { code: "K57.30", description: "Diverticulosis of large intestine without perforation or abscess without bleeding", category: "Gastrointestinal" },
  { code: "K57.92", description: "Diverticulitis of intestine, unspecified, without perforation or abscess with bleeding", category: "Gastrointestinal" },
  { code: "K59.00", description: "Constipation, unspecified", category: "Gastrointestinal" },
  { code: "K70.30", description: "Alcoholic cirrhosis of liver without ascites", category: "Gastrointestinal" },
  { code: "K72.90", description: "Hepatic failure, unspecified, without coma", category: "Gastrointestinal" },
  { code: "K74.60", description: "Unspecified cirrhosis of liver", category: "Gastrointestinal" },
  { code: "K80.20", description: "Calculus of gallbladder without cholecystitis without obstruction", category: "Gastrointestinal" },
  { code: "K85.90", description: "Acute pancreatitis without necrosis or infection, unspecified", category: "Gastrointestinal" },
  { code: "K92.0", description: "Hematemesis", category: "Gastrointestinal" },
  { code: "K92.1", description: "Melena", category: "Gastrointestinal" },
  { code: "K92.2", description: "Gastrointestinal hemorrhage, unspecified", category: "Gastrointestinal" },
  { code: "R10.9", description: "Unspecified abdominal pain", category: "Gastrointestinal" },
  { code: "R11.2", description: "Nausea with vomiting, unspecified", category: "Gastrointestinal" },
  { code: "R19.7", description: "Diarrhea, unspecified", category: "Gastrointestinal" },

  // Musculoskeletal
  { code: "M17.11", description: "Primary osteoarthritis, right knee", category: "Musculoskeletal" },
  { code: "M17.12", description: "Primary osteoarthritis, left knee", category: "Musculoskeletal" },
  { code: "M16.11", description: "Primary osteoarthritis, right hip", category: "Musculoskeletal" },
  { code: "M19.90", description: "Unspecified osteoarthritis, unspecified site", category: "Musculoskeletal" },
  { code: "M25.561", description: "Pain in right knee", category: "Musculoskeletal" },
  { code: "M25.50", description: "Pain in unspecified joint", category: "Musculoskeletal" },
  { code: "M48.06", description: "Spinal stenosis, lumbar region", category: "Musculoskeletal" },
  { code: "M51.36", description: "Other intervertebral disc degeneration, lumbar region", category: "Musculoskeletal" },
  { code: "M54.5", description: "Low back pain", category: "Musculoskeletal" },
  { code: "M54.2", description: "Cervicalgia", category: "Musculoskeletal" },
  { code: "M62.81", description: "Muscle weakness (generalized)", category: "Musculoskeletal" },
  { code: "M79.1", description: "Myalgia", category: "Musculoskeletal" },
  { code: "M79.601", description: "Pain in right arm", category: "Musculoskeletal" },
  { code: "M79.604", description: "Pain in right leg", category: "Musculoskeletal" },
  { code: "M80.08XA", description: "Age-related osteoporosis with current pathological fracture, other site, initial encounter", category: "Musculoskeletal" },
  { code: "S06.0X0A", description: "Concussion without loss of consciousness, initial encounter", category: "Musculoskeletal" },
  { code: "S22.000A", description: "Wedge compression fracture of unspecified thoracic vertebra, initial encounter", category: "Musculoskeletal" },
  { code: "S42.001A", description: "Fracture of unspecified part of right clavicle, initial encounter", category: "Musculoskeletal" },
  { code: "S52.501A", description: "Unspecified fracture of the lower end of right radius, initial encounter", category: "Musculoskeletal" },
  { code: "S72.001A", description: "Fracture of unspecified part of neck of right femur, initial encounter", category: "Musculoskeletal" },
  { code: "S72.141A", description: "Displaced intertrochanteric fracture of right femur, initial encounter", category: "Musculoskeletal" },
  { code: "S82.101A", description: "Unspecified fracture of upper end of right tibia, initial encounter", category: "Musculoskeletal" },
  { code: "T14.90XA", description: "Injury, unspecified, initial encounter", category: "Musculoskeletal" },

  // Neurological
  { code: "G20", description: "Parkinson's disease", category: "Neurological" },
  { code: "G30.9", description: "Alzheimer's disease, unspecified", category: "Neurological" },
  { code: "G31.84", description: "Mild cognitive impairment of uncertain or unknown etiology", category: "Neurological" },
  { code: "G40.909", description: "Epilepsy, unspecified, not intractable, without status epilepticus", category: "Neurological" },
  { code: "G43.909", description: "Migraine, unspecified, not intractable, without status migrainosus", category: "Neurological" },
  { code: "G45.9", description: "Transient cerebral ischemic attack, unspecified", category: "Neurological" },
  { code: "G47.00", description: "Insomnia, unspecified", category: "Neurological" },
  { code: "G47.33", description: "Obstructive sleep apnea (adult) (pediatric)", category: "Neurological" },
  { code: "G62.9", description: "Polyneuropathy, unspecified", category: "Neurological" },
  { code: "G89.29", description: "Other chronic pain", category: "Neurological" },
  { code: "G93.1", description: "Anoxic brain damage, not elsewhere classified", category: "Neurological" },
  { code: "R26.81", description: "Unsteadiness on feet", category: "Neurological" },
  { code: "R40.2043", description: "Glasgow coma scale score 13-15, unspecified time", category: "Neurological" },
  { code: "R42", description: "Dizziness and giddiness", category: "Neurological" },
  { code: "R55", description: "Syncope and collapse", category: "Neurological" },
  { code: "R56.9", description: "Unspecified convulsions", category: "Neurological" },

  // Renal / Genitourinary
  { code: "N17.9", description: "Acute kidney failure, unspecified", category: "Renal" },
  { code: "N18.3", description: "Chronic kidney disease, stage 3", category: "Renal" },
  { code: "N18.4", description: "Chronic kidney disease, stage 4", category: "Renal" },
  { code: "N18.6", description: "End stage renal disease", category: "Renal" },
  { code: "N20.0", description: "Calculus of kidney", category: "Renal" },
  { code: "N28.9", description: "Disorder of kidney and ureter, unspecified", category: "Renal" },
  { code: "N30.00", description: "Acute cystitis without hematuria", category: "Renal" },
  { code: "N39.0", description: "Urinary tract infection, site not specified", category: "Renal" },
  { code: "N40.1", description: "Benign prostatic hyperplasia with lower urinary tract symptoms", category: "Renal" },
  { code: "N17.0", description: "Acute kidney failure with tubular necrosis", category: "Renal" },
  { code: "R31.9", description: "Hematuria, unspecified", category: "Renal" },
  { code: "R33.9", description: "Retention of urine, unspecified", category: "Renal" },

  // Oncological
  { code: "C34.90", description: "Malignant neoplasm of unspecified part of unspecified bronchus or lung", category: "Oncological" },
  { code: "C50.919", description: "Malignant neoplasm of unspecified site of unspecified female breast", category: "Oncological" },
  { code: "C61", description: "Malignant neoplasm of prostate", category: "Oncological" },
  { code: "C18.9", description: "Malignant neoplasm of colon, unspecified", category: "Oncological" },
  { code: "C25.9", description: "Malignant neoplasm of pancreas, unspecified", category: "Oncological" },
  { code: "C64.9", description: "Malignant neoplasm of unspecified kidney, except renal pelvis", category: "Oncological" },
  { code: "C67.9", description: "Malignant neoplasm of bladder, unspecified", category: "Oncological" },
  { code: "C71.9", description: "Malignant neoplasm of brain, unspecified", category: "Oncological" },
  { code: "C77.0", description: "Secondary and unspecified malignant neoplasm of lymph nodes of head, face and neck", category: "Oncological" },
  { code: "C80.1", description: "Malignant (primary) neoplasm, unspecified", category: "Oncological" },
  { code: "C91.00", description: "Acute lymphoblastic leukemia not having achieved remission", category: "Oncological" },
  { code: "D64.9", description: "Anemia, unspecified", category: "Oncological" },
  { code: "Z51.11", description: "Encounter for antineoplastic chemotherapy", category: "Oncological" },
  { code: "Z51.12", description: "Encounter for antineoplastic immunotherapy", category: "Oncological" },

  // Mental Health
  { code: "F32.9", description: "Major depressive disorder, single episode, unspecified", category: "Mental Health" },
  { code: "F33.1", description: "Major depressive disorder, recurrent, moderate", category: "Mental Health" },
  { code: "F41.1", description: "Generalized anxiety disorder", category: "Mental Health" },
  { code: "F41.9", description: "Anxiety disorder, unspecified", category: "Mental Health" },
  { code: "F43.10", description: "Post-traumatic stress disorder, unspecified", category: "Mental Health" },
  { code: "F43.23", description: "Adjustment disorder with mixed anxiety and depressed mood", category: "Mental Health" },
  { code: "F05", description: "Delirium due to known physiological condition", category: "Mental Health" },
  { code: "F10.20", description: "Alcohol dependence, uncomplicated", category: "Mental Health" },
  { code: "F11.20", description: "Opioid dependence, uncomplicated", category: "Mental Health" },
  { code: "F17.210", description: "Nicotine dependence, cigarettes, uncomplicated", category: "Mental Health" },
  { code: "F20.9", description: "Schizophrenia, unspecified", category: "Mental Health" },
  { code: "F31.9", description: "Bipolar disorder, unspecified", category: "Mental Health" },
  { code: "F03.90", description: "Unspecified dementia without behavioral disturbance", category: "Mental Health" },

  // Infectious Disease
  { code: "A41.9", description: "Sepsis, unspecified organism", category: "Infectious Disease" },
  { code: "A41.01", description: "Sepsis due to Methicillin susceptible Staphylococcus aureus", category: "Infectious Disease" },
  { code: "A49.9", description: "Bacterial infection, unspecified", category: "Infectious Disease" },
  { code: "B96.20", description: "Unspecified Escherichia coli as the cause of diseases classified elsewhere", category: "Infectious Disease" },
  { code: "B34.9", description: "Viral infection, unspecified", category: "Infectious Disease" },
  { code: "B37.9", description: "Candidiasis, unspecified", category: "Infectious Disease" },
  { code: "R65.20", description: "Severe sepsis without septic shock", category: "Infectious Disease" },
  { code: "R65.21", description: "Severe sepsis with septic shock", category: "Infectious Disease" },
  { code: "R50.9", description: "Fever, unspecified", category: "Infectious Disease" },
  { code: "A04.7", description: "Enterocolitis due to Clostridium difficile", category: "Infectious Disease" },

  // Dermatological / Wound Care
  { code: "L03.115", description: "Cellulitis of right lower limb", category: "Dermatological" },
  { code: "L89.153", description: "Pressure ulcer of sacral region, stage 3", category: "Dermatological" },
  { code: "L97.409", description: "Non-pressure chronic ulcer of unspecified heel and midfoot with unspecified severity", category: "Dermatological" },
  { code: "L98.419", description: "Non-pressure chronic ulcer of buttock with unspecified severity", category: "Dermatological" },

  // Hematological
  { code: "D62", description: "Acute posthemorrhagic anemia", category: "Hematological" },
  { code: "D68.9", description: "Coagulation defect, unspecified", category: "Hematological" },
  { code: "D69.6", description: "Thrombocytopenia, unspecified", category: "Hematological" },
  { code: "D72.829", description: "Elevated white blood cell count, unspecified", category: "Hematological" },

  // Other / Symptoms & Signs
  { code: "R53.83", description: "Other fatigue", category: "Other" },
  { code: "R63.4", description: "Abnormal weight loss", category: "Other" },
  { code: "Z87.891", description: "Personal history of nicotine dependence", category: "Other" },
  { code: "Z79.4", description: "Long term (current) use of insulin", category: "Other" },
  { code: "Z79.01", description: "Long term (current) use of anticoagulants", category: "Other" },
  { code: "Z66", description: "Do not resuscitate", category: "Other" },
  { code: "Z68.41", description: "Body mass index [BMI] 40.0-44.9, adult", category: "Other" },
  { code: "Z91.14", description: "Patient's other noncompliance with medication regimen", category: "Other" },
  { code: "Z99.2", description: "Dependence on renal dialysis", category: "Other" },
  { code: "Z95.1", description: "Presence of aortocoronary bypass graft", category: "Other" },
  { code: "R41.82", description: "Altered mental status, unspecified", category: "Other" },
  { code: "R09.2", description: "Respiratory arrest", category: "Other" },
  { code: "I46.9", description: "Cardiac arrest, cause unspecified", category: "Other" },
  { code: "T81.4XXA", description: "Infection following a procedure, initial encounter", category: "Other" },
  { code: "T88.9XXA", description: "Complication of surgical and medical care, unspecified, initial encounter", category: "Other" },
  { code: "I25.700", description: "Atherosclerosis of coronary artery bypass graft(s), unspecified, with angina pectoris with documented spasm", category: "Cardiovascular" },
  { code: "I34.0", description: "Nonrheumatic mitral (valve) insufficiency", category: "Cardiovascular" },
  { code: "I49.9", description: "Cardiac arrhythmia, unspecified", category: "Cardiovascular" },
  { code: "J43.9", description: "Emphysema, unspecified", category: "Respiratory" },
  { code: "J47.9", description: "Bronchiectasis, uncomplicated", category: "Respiratory" },
  { code: "E16.2", description: "Hypoglycemia, unspecified", category: "Endocrine" },
  { code: "E27.40", description: "Unspecified adrenocortical insufficiency", category: "Endocrine" },
  { code: "K26.9", description: "Duodenal ulcer, unspecified as acute or chronic, without hemorrhage or perforation", category: "Gastrointestinal" },
  { code: "K76.0", description: "Fatty (change of) liver, not elsewhere classified", category: "Gastrointestinal" },
  { code: "M06.9", description: "Rheumatoid arthritis, unspecified", category: "Musculoskeletal" },
  { code: "M75.101", description: "Unspecified rotator cuff tear or rupture of right shoulder, not specified as traumatic", category: "Musculoskeletal" },
  { code: "G35", description: "Multiple sclerosis", category: "Neurological" },
  { code: "G56.01", description: "Carpal tunnel syndrome, right upper limb", category: "Neurological" },
  { code: "N19", description: "Unspecified kidney failure", category: "Renal" },
  { code: "N23", description: "Unspecified renal colic", category: "Renal" },
  { code: "C22.9", description: "Malignant neoplasm of liver, not specified as primary or secondary", category: "Oncological" },
  { code: "C43.9", description: "Malignant melanoma of skin, unspecified", category: "Oncological" },
  { code: "F42.9", description: "Obsessive-compulsive disorder, unspecified", category: "Mental Health" },
  { code: "F90.9", description: "Attention-deficit hyperactivity disorder, unspecified type", category: "Mental Health" },
  { code: "B95.62", description: "Methicillin resistant Staphylococcus aureus infection as the cause of diseases classified elsewhere", category: "Infectious Disease" },
];
